# Generated by Django 3.0.6 on 2020-05-25 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FioRassilki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('surname', models.CharField(max_length=128, verbose_name='Отчество')),
                ('dolzhnost', models.CharField(max_length=128, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'ФИО Рассылки',
                'verbose_name_plural': 'ФИО Рассылки',
            },
        ),
        migrations.CreateModel(
            name='OrganCrypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256, verbose_name='Компания')),
                ('region', models.CharField(max_length=256, verbose_name='Регион')),
                ('fio', models.CharField(blank=True, max_length=256, null=True, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Орган криптозащиты',
                'verbose_name_plural': 'Органы криптозащиты',
            },
        ),
        migrations.CreateModel(
            name='SkziName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, verbose_name='Тип')),
                ('firma', models.CharField(max_length=256, verbose_name='Фирма')),
                ('version', models.CharField(max_length=32, verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Наименование СКЗИ',
                'verbose_name_plural': 'Наименования СКЗИ',
            },
        ),
        migrations.CreateModel(
            name='Skzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_n', models.CharField(max_length=32)),
                ('ekz_n', models.CharField(blank=True, max_length=32)),
                ('date_poluch', models.DateField(blank=True, null=True)),
                ('nomer_poluch', models.CharField(max_length=64)),
                ('date_sopr', models.DateField()),
                ('nomer_sopr', models.CharField(default='', max_length=32)),
                ('date_podtv', models.DateField()),
                ('nomer_podtv', models.CharField(default='', max_length=32)),
                ('podtv', models.BooleanField(default=False)),
                ('vozvr_date_sopr', models.DateField(blank=True, null=True)),
                ('vozvr_nomer_sopr', models.CharField(blank=True, default='', max_length=32)),
                ('vozvr_date_podtv', models.DateField(blank=True, null=True)),
                ('vozvr_nomer_podtv', models.CharField(blank=True, default='', max_length=32)),
                ('date_vvod', models.DateField()),
                ('date_vivod', models.DateField(blank=True, null=True)),
                ('date_unichtozh', models.DateField(blank=True, null=True)),
                ('nomer_acta', models.CharField(max_length=32)),
                ('act_podtv', models.BooleanField(default=False)),
                ('primechanie', models.CharField(max_length=1024)),
                ('from_organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skzis_from', to='Skzi.OrganCrypto')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Skzi.SkziName')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skzis_to', to='Skzi.FioRassilki')),
            ],
        ),
    ]
