# Generated by Django 3.0.6 on 2020-05-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skzi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skzi',
            options={'verbose_name': 'Запись СКЗИ', 'verbose_name_plural': 'Записи СКЗИ'},
        ),
    ]
