# Generated by Django 3.0.6 on 2020-05-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skzi', '0002_auto_20200525_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skzi',
            name='date_podtv',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skzi',
            name='date_sopr',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skzi',
            name='date_vvod',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skzi',
            name='nomer_acta',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='skzi',
            name='nomer_podtv',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='skzi',
            name='nomer_poluch',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='skzi',
            name='nomer_sopr',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='skzi',
            name='primechanie',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='skzi',
            name='vozvr_nomer_podtv',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='skzi',
            name='vozvr_nomer_sopr',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
