# Generated by Django 3.0.6 on 2020-05-25 18:32

import Ispdn.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pdn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField(verbose_name='Номер')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('file', models.FileField(null=True, upload_to=Ispdn.models.Instruct.content_file_name)),
                ('ovetstv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pdn.Person', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'Инструкции',
            },
        ),
        migrations.CreateModel(
            name='ProgOb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField(verbose_name='Номер')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('file', models.FileField(null=True, upload_to=Ispdn.models.ProgOb.content_file_name)),
            ],
            options={
                'verbose_name': 'ПО',
                'verbose_name_plural': 'ПО',
            },
        ),
        migrations.CreateModel(
            name='Rukovodstvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField(verbose_name='Номер')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('file', models.FileField(null=True, upload_to=Ispdn.models.Rukovodstvo.content_file_name)),
            ],
            options={
                'verbose_name': 'Руководство',
                'verbose_name_plural': 'Руководства',
            },
        ),
        migrations.CreateModel(
            name='Prikaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField(verbose_name='Номер')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('file', models.FileField(null=True, upload_to=Ispdn.models.Prikaz.content_file_name)),
                ('ovetstv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pdn.Person', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Приказ',
                'verbose_name_plural': 'Приказы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Polozhenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField(verbose_name='Номер')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('file', models.FileField(null=True, upload_to=Ispdn.models.Polozhenie.content_file_name)),
                ('ovetstv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pdn.Person', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Положение',
                'verbose_name_plural': 'Положения',
            },
        ),
        migrations.CreateModel(
            name='Ispdn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('instruct', models.ManyToManyField(blank=True, related_name='ispdns', to='Ispdn.Instruct')),
                ('po', models.ManyToManyField(blank=True, related_name='ispdns', to='Ispdn.ProgOb')),
                ('polozhenie', models.ManyToManyField(blank=True, related_name='ispdns', to='Ispdn.Polozhenie')),
                ('prikaz', models.ManyToManyField(blank=True, related_name='ispdns', to='Ispdn.Prikaz')),
                ('rukovodstvo', models.ManyToManyField(blank=True, related_name='ispdns', to='Ispdn.Rukovodstvo')),
            ],
            options={
                'verbose_name': 'ИСПДн',
                'verbose_name_plural': 'ИСПДн',
            },
        ),
    ]
