# Generated by Django 3.0.6 on 2020-05-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ispdn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ispdn',
            name='nomer',
            field=models.CharField(max_length=32),
        ),
    ]
