# Generated by Django 3.0.6 on 2020-05-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ispdn', '0002_auto_20200525_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ispdn',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ispdn',
            name='nomer',
            field=models.CharField(max_length=32, verbose_name='Номер'),
        ),
    ]
