# Generated by Django 3.0.6 on 2020-05-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ispdn', '0004_auto_20200526_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='ispdn',
            name='raznoe',
            field=models.ManyToManyField(blank=True, related_name='ispdns', to='Ispdn.Raznoe'),
        ),
    ]
