# Generated by Django 3.0.6 on 2020-05-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ispdn', '0005_ispdn_raznoe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruct',
            options={'ordering': ['-id'], 'verbose_name': 'Инструкция', 'verbose_name_plural': 'Инструкции'},
        ),
        migrations.AlterModelOptions(
            name='polozhenie',
            options={'ordering': ['-id'], 'verbose_name': 'Положение', 'verbose_name_plural': 'Положения'},
        ),
        migrations.AlterModelOptions(
            name='progob',
            options={'ordering': ['-id'], 'verbose_name': 'ПО', 'verbose_name_plural': 'ПО'},
        ),
        migrations.AlterModelOptions(
            name='raznoe',
            options={'ordering': ['-id'], 'verbose_name': 'Разное', 'verbose_name_plural': 'Разное'},
        ),
        migrations.AlterModelOptions(
            name='rukovodstvo',
            options={'ordering': ['-id'], 'verbose_name': 'Руководство', 'verbose_name_plural': 'Руководства'},
        ),
    ]
