# Generated by Django 3.0.6 on 2020-05-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dolzhnost',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='gr_key',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
