# Generated by Django 3.0.6 on 2020-05-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0009_auto_20200522_1758'),
        ('Accounts', '0002_auto_20200522_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otdel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Security.OtdelIR'),
        ),
    ]
