# Generated by Django 3.0.6 on 2020-05-23 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FioRassilki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('surname', models.CharField(max_length=128, verbose_name='Отчество')),
                ('dolzhnost', models.CharField(max_length=128, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'ФИО Рассылки',
                'verbose_name_plural': 'ФИО Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Instruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField(verbose_name='Номер')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'Инструкции',
            },
        ),
        migrations.CreateModel(
            name='OrganCrypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256, verbose_name='Компания')),
                ('region', models.CharField(max_length=256, verbose_name='Регион')),
                ('fio', models.CharField(blank=True, max_length=256, null=True, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Орган криптозащиты',
                'verbose_name_plural': 'Органы криптозащиты',
            },
        ),
        migrations.CreateModel(
            name='OtdelIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Отдел ИР',
                'verbose_name_plural': 'Отделы ИР',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('birth_date', models.DateField()),
                ('fakultet', models.CharField(max_length=128)),
                ('podrazd', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Сотрудник/Студент',
                'verbose_name_plural': 'Сотрудники/Студенты',
            },
        ),
        migrations.CreateModel(
            name='ProgOb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField(verbose_name='Номер')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'ПО',
                'verbose_name_plural': 'ПО',
            },
        ),
        migrations.CreateModel(
            name='Rukovodstvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField(verbose_name='Номер')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Руководство',
                'verbose_name_plural': 'Руководства',
            },
        ),
        migrations.CreateModel(
            name='SkziName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, verbose_name='Тип')),
                ('firma', models.CharField(max_length=256, verbose_name='Фирма')),
                ('version', models.CharField(max_length=32, verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Наименование СКЗИ',
                'verbose_name_plural': 'Наименования СКЗИ',
            },
        ),
        migrations.CreateModel(
            name='Skzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_n', models.CharField(max_length=32)),
                ('ekz_n', models.CharField(blank=True, max_length=32)),
                ('date_poluch', models.DateField(blank=True, null=True)),
                ('nomer_poluch', models.CharField(max_length=64)),
                ('date_sopr', models.DateField()),
                ('nomer_sopr', models.CharField(default='', max_length=32)),
                ('date_podtv', models.DateField()),
                ('nomer_podtv', models.CharField(default='', max_length=32)),
                ('podtv', models.BooleanField(default=False)),
                ('vozvr_date_sopr', models.DateField(blank=True, null=True)),
                ('vozvr_nomer_sopr', models.CharField(blank=True, default='', max_length=32)),
                ('vozvr_date_podtv', models.DateField(blank=True, null=True)),
                ('vozvr_nomer_podtv', models.CharField(blank=True, default='', max_length=32)),
                ('date_vvod', models.DateField()),
                ('date_vivod', models.DateField(blank=True, null=True)),
                ('date_unichtozh', models.DateField(blank=True, null=True)),
                ('nomer_acta', models.CharField(max_length=32)),
                ('act_podtv', models.BooleanField(default=False)),
                ('primechanie', models.CharField(max_length=1024)),
                ('from_organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skzis_from', to='Security.OrganCrypto')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Security.SkziName')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skzis_to', to='Security.FioRassilki')),
            ],
        ),
        migrations.CreateModel(
            name='Prikaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField(verbose_name='Номер')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('ovetstv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Security.Person', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Приказ',
                'verbose_name_plural': 'Приказы',
            },
        ),
        migrations.CreateModel(
            name='Polozhenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField(verbose_name='Номер')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('ovetstv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Security.Person', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Положение',
                'verbose_name_plural': 'Положения',
            },
        ),
        migrations.CreateModel(
            name='Pdn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nalichie', models.BooleanField()),
                ('preson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdns', to='Security.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Ispdn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('instruct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Security.Instruct')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Security.ProgOb')),
                ('polozhenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Security.Polozhenie')),
                ('prikaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Security.Prikaz')),
                ('rukovodstvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Security.Rukovodstvo')),
            ],
        ),
        migrations.AddField(
            model_name='instruct',
            name='ovetstv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Security.Person', verbose_name='Ответственный'),
        ),
    ]
