# Generated by Django 3.0.6 on 2020-05-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FioRassilki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('dolzhnost', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Instruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Ispdn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('instruct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Security.Instruct')),
            ],
        ),
        migrations.CreateModel(
            name='OrganCrypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=256)),
                ('fio', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('birth_date', models.DateField()),
                ('fakultet', models.CharField(max_length=128)),
                ('podrazd', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProgOb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Rukovodstvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SkziName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('firma', models.CharField(max_length=256)),
                ('version', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Skzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_n', models.CharField(max_length=32)),
                ('ekz_n', models.CharField(max_length=32)),
                ('date_and_n', models.CharField(max_length=64)),
                ('date_sopr', models.DateField()),
                ('date_podtv', models.DateField()),
                ('podtv', models.BooleanField()),
                ('date_1', models.DateField()),
                ('date_2', models.DateField()),
                ('date_3', models.DateField()),
                ('date_4', models.DateField()),
                ('date_5', models.DateField()),
                ('nomer_acta', models.CharField(max_length=32)),
                ('primechanie', models.CharField(max_length=1024)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skzis_from', to='Security.Person')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Security.SkziName')),
                ('rassilka', models.ManyToManyField(to='Security.FioRassilki')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skzis_to', to='Security.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Prikaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('ovetstv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Security.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Polozhenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('ovetstv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Security.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Pdn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nalichie', models.BooleanField()),
                ('preson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdns', to='Security.Person')),
            ],
        ),
        migrations.CreateModel(
            name='OtdelIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispdn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otdeliIR', to='Security.Ispdn')),
                ('pdn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otdeliIR', to='Security.Pdn')),
                ('skzi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otdeliIR', to='Security.Skzi')),
            ],
        ),
        migrations.AddField(
            model_name='ispdn',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Security.ProgOb'),
        ),
        migrations.AddField(
            model_name='ispdn',
            name='polozhenie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Security.Polozhenie'),
        ),
        migrations.AddField(
            model_name='ispdn',
            name='prikaz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Security.Prikaz'),
        ),
        migrations.AddField(
            model_name='ispdn',
            name='rukovodstvo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Security.Rukovodstvo'),
        ),
        migrations.AddField(
            model_name='instruct',
            name='ovetstv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Security.Person'),
        ),
    ]
