# Generated by Django 3.0.6 on 2020-05-23 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ispdn',
            name='instruct',
        ),
        migrations.RemoveField(
            model_name='ispdn',
            name='po',
        ),
        migrations.RemoveField(
            model_name='ispdn',
            name='polozhenie',
        ),
        migrations.RemoveField(
            model_name='ispdn',
            name='prikaz',
        ),
        migrations.RemoveField(
            model_name='ispdn',
            name='rukovodstvo',
        ),
    ]
