# Generated by Django 3.0.6 on 2020-05-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0002_auto_20200522_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skzi',
            old_name='date_2',
            new_name='vozvr_date_podtv',
        ),
    ]
