# Generated by Django 3.0.6 on 2020-05-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0003_auto_20200523_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='prikaz',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
