# Generated by Django 3.0.6 on 2020-05-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0004_auto_20200522_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skzi',
            old_name='date_4',
            new_name='date_vivod',
        ),
    ]
