# Generated by Django 3.0.6 on 2020-05-24 01:37

import Security.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0004_prikaz_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prikaz',
            options={'ordering': ['-id'], 'verbose_name': 'Приказ', 'verbose_name_plural': 'Приказы'},
        ),
        migrations.AlterField(
            model_name='prikaz',
            name='file',
            field=models.FileField(null=True, upload_to=Security.models.Prikaz.content_file_name),
        ),
    ]
