# Generated by Django 3.0.6 on 2020-05-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0005_auto_20200524_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ispdn',
            options={'verbose_name': 'ИСПДн', 'verbose_name_plural': 'ИСПДн'},
        ),
        migrations.AlterField(
            model_name='ispdn',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ispdn',
            name='instruct',
            field=models.ManyToManyField(blank=True, related_name='ispdns', to='Security.Instruct'),
        ),
        migrations.AlterField(
            model_name='ispdn',
            name='po',
            field=models.ManyToManyField(blank=True, related_name='ispdns', to='Security.ProgOb'),
        ),
        migrations.AlterField(
            model_name='ispdn',
            name='polozhenie',
            field=models.ManyToManyField(blank=True, related_name='ispdns', to='Security.Polozhenie'),
        ),
        migrations.AlterField(
            model_name='ispdn',
            name='prikaz',
            field=models.ManyToManyField(blank=True, related_name='ispdns', to='Security.Prikaz'),
        ),
        migrations.AlterField(
            model_name='ispdn',
            name='rukovodstvo',
            field=models.ManyToManyField(blank=True, related_name='ispdns', to='Security.Rukovodstvo'),
        ),
        migrations.AlterField(
            model_name='ispdn',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
