# Generated by Django 3.0.6 on 2020-05-22 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0006_auto_20200522_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiorassilki',
            options={'verbose_name': 'ФИО Рассылки', 'verbose_name_plural': 'ФИО Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='instruct',
            options={'verbose_name': 'Инструкция', 'verbose_name_plural': 'Инструкции'},
        ),
        migrations.AlterModelOptions(
            name='organcrypto',
            options={'verbose_name': 'Орган криптозащиты', 'verbose_name_plural': 'Органы криптозащиты'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Сотрудник/Студент', 'verbose_name_plural': 'Сотрудники/Студенты'},
        ),
        migrations.AlterModelOptions(
            name='polozhenie',
            options={'verbose_name': 'Положение', 'verbose_name_plural': 'Положения'},
        ),
        migrations.AlterModelOptions(
            name='prikaz',
            options={'verbose_name': 'Приказ', 'verbose_name_plural': 'Приказы'},
        ),
        migrations.AlterModelOptions(
            name='progob',
            options={'verbose_name': 'ПО', 'verbose_name_plural': 'ПО'},
        ),
        migrations.AlterModelOptions(
            name='rukovodstvo',
            options={'verbose_name': 'Руководство', 'verbose_name_plural': 'Руководства'},
        ),
        migrations.AlterModelOptions(
            name='skziname',
            options={'verbose_name': 'Наименование СКЗИ', 'verbose_name_plural': 'Наименования СКЗИ'},
        ),
        migrations.RemoveField(
            model_name='otdelir',
            name='ispdn',
        ),
        migrations.RemoveField(
            model_name='otdelir',
            name='pdn',
        ),
        migrations.RemoveField(
            model_name='otdelir',
            name='skzi',
        ),
        migrations.AlterField(
            model_name='fiorassilki',
            name='dolzhnost',
            field=models.CharField(max_length=128, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='fiorassilki',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='fiorassilki',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='fiorassilki',
            name='surname',
            field=models.CharField(max_length=128, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='instruct',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='instruct',
            name='nomer',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='instruct',
            name='ovetstv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Security.Person', verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='organcrypto',
            name='company',
            field=models.CharField(max_length=256, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='organcrypto',
            name='fio',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='organcrypto',
            name='region',
            field=models.CharField(max_length=256, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='polozhenie',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='polozhenie',
            name='nomer',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='polozhenie',
            name='ovetstv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Security.Person', verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='prikaz',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='prikaz',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='prikaz',
            name='nomer',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='prikaz',
            name='ovetstv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Security.Person', verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='progob',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='progob',
            name='nomer',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='rukovodstvo',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rukovodstvo',
            name='nomer',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='skziname',
            name='firma',
            field=models.CharField(max_length=256, verbose_name='Фирма'),
        ),
        migrations.AlterField(
            model_name='skziname',
            name='type',
            field=models.CharField(max_length=128, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='skziname',
            name='version',
            field=models.CharField(max_length=32, verbose_name='Версия'),
        ),
    ]
