# Generated by Django 3.0.6 on 2020-05-25 00:27

import Security.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0006_auto_20200524_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruct',
            name='file',
            field=models.FileField(null=True, upload_to=Security.models.Instruct.content_file_name),
        ),
        migrations.AddField(
            model_name='polozhenie',
            name='file',
            field=models.FileField(null=True, upload_to=Security.models.Polozhenie.content_file_name),
        ),
        migrations.AddField(
            model_name='progob',
            name='file',
            field=models.FileField(null=True, upload_to=Security.models.ProgOb.content_file_name),
        ),
        migrations.AddField(
            model_name='rukovodstvo',
            name='file',
            field=models.FileField(null=True, upload_to=Security.models.Rukovodstvo.content_file_name),
        ),
    ]
