# Generated by Django 3.0.6 on 2020-05-22 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0007_auto_20200522_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='ispdn',
            name='otdel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ispdns', to='Security.OtdelIR'),
        ),
        migrations.AddField(
            model_name='otdelir',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pdn',
            name='otdel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pdns', to='Security.OtdelIR'),
        ),
        migrations.AddField(
            model_name='skzi',
            name='otdel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='skzis', to='Security.OtdelIR'),
        ),
    ]
