# Generated by Django 3.0.6 on 2020-05-22 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0008_auto_20200522_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otdelir',
            options={'verbose_name': 'Отдел ИР', 'verbose_name_plural': 'Отделы ИР'},
        ),
        migrations.AlterField(
            model_name='ispdn',
            name='otdel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ispdns', to='Security.OtdelIR', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='otdelir',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pdn',
            name='otdel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdns', to='Security.OtdelIR', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='skzi',
            name='otdel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skzis', to='Security.OtdelIR', verbose_name='Отдел'),
        ),
    ]
