# Generated by Django 3.0.6 on 2020-05-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pdn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdn',
            options={'verbose_name': 'ПДн', 'verbose_name_plural': 'ПДн'},
        ),
    ]
