# Generated by Django 3.0.6 on 2020-05-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pdn', '0003_auto_20200525_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdn',
            old_name='preson',
            new_name='person',
        ),
    ]
