# Generated by Django 3.0.6 on 2020-05-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pdn', '0004_auto_20200526_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sogl_raspr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='soglasie',
            field=models.BooleanField(default=False),
        ),
    ]
