# Generated by Django 3.0.6 on 2020-05-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pdn', '0005_auto_20200526_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-id'], 'verbose_name': 'Сотрудник/Студент', 'verbose_name_plural': 'Сотрудники/Студенты'},
        ),
        migrations.AlterField(
            model_name='person',
            name='sogl_raspr',
            field=models.BooleanField(default=False, verbose_name='Согласие на распространение персональных данных'),
        ),
        migrations.AlterField(
            model_name='person',
            name='soglasie',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
    ]
