# Generated by Django 3.0.6 on 2020-05-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pdn', '0006_auto_20200526_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdn',
        ),
    ]
