# Generated by Django 3.0.6 on 2020-05-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pdn', '0008_auto_20200529_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fakultet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pdn.Fakultet', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='person',
            name='podrazd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pdn.Podrazdelenie', verbose_name='Подразделение'),
        ),
    ]
